export const tileSize = 16
export const viewTiles = 9
export const canvasTiles = viewTiles + 1
export const centerTile = ~~( viewTiles / 2 )
export const mapSize = 128
export const animTime = 500
export const waterBorder = ~~( mapSize / 16 )
export const landBorder = ~~( mapSize / 6 )
export const gridTiles = 10
export const gridSize = ~~( mapSize / gridTiles )
export const initialMonsterCount = ~~( mapSize / 3 )
export const sunrise = 6
export const sunset = 18